services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ny_taxi
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - type: bind
        source: ./postgres_data
        target: /var/lib/postgresql/data
        read_only: false
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 30s
      retries: 10
    networks:
      - dezc

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "8080:80"
    volumes:
      - ./data_pgadmin:/var/lib/pgadmin
    networks:
      - dezc

networks:
  dezc:
    name: dezc
    driver: bridge